describe 'enumerable methods' do
  it 'returns true if block never returns false or nil' do
    array1 = [nil, 99, 78, true]
    expect(array1.all?).to eq false
    expect(%w[bat, bird, big].all? { |word| word[0] == 'b' }).to eq true
  end

  it 'returns true if block ever returns a value other than false or nil' do
    array1 = [nil, 99, 78, true]
    array2 = [false, nil]
    expect(array1.any?).to eq true
    expect(%w[bat, bird, big].any? { |word| word[0] == 'b' }).to eq true
    expect(array2.any?).to eq false
  end

  it 'returns the number of items enumerated over' do
    array1 = [nil, 99, 78, true]
    expect(array1.count).to eq 4
  end

  it 'enumerates over a block and returns that block repeated x times, or forever if none or nil is given' do
    letters = ['a', 'b', 'c']
    full_letter = []
    letters.cycle(2) { |letter| full_letter << letter}
    expect(full_letter).to eq ['a', 'b', 'c','a', 'b', 'c']
  end

  it 'drops the first however many numbers from a block' do
    array1 = [1,2,3,4,5,6,7]
    expect(array1.drop(4)).to eq [5,6,7]
  end

  it 'drops an element from an array while a condition is true' do
    a = [1, 2, 3, 4, 5, 0]
    expect(a.drop_while { |i| i < 3 }).to eq [3, 4, 5, 0]
  end

  it 'iterates to give the different combinations from 0 to array length of a given number' do
    array = [1, 2, 3, 4]
    expect(array.each_cons(2).to_a).to eq [[1, 2], [2, 3], [3, 4]]
  end

  it 'iterates to give the given number as a slice of an array length' do
    array = [1, 2, 3, 4]
    expect(array.each_slice(2).to_a).to eq [[1, 2], [3, 4]]
  end

  it 'iterates over an element and its index' do
    array = [10, 20, 30, 40]
    array2 = []
    array.each_with_index { |num, index| array2 << num + index + 1}
    expect(array2).to eq [11, 22, 33, 44]
  end

  it 'finds the first element that is truthy ' do
    array = [1,2,3]
    expect(array.find { |num| num % 2 == 0 }).to eq 2
    expect(array.find { |num| num.odd? }).to eq 1
  end

  it 'finds all elements that are truthy and returns result an array' do
    array = [1,2,3]
    expect(array.find_all { |num| num % 2 == 0 }).to eq [2]
    expect(array.find_all { |num| num.odd? }).to eq [1, 3]
    expect(array.find_all { |num| num > 10 }).to eq []
  end

  it 'returns true or false if there is one' do
    array = [1,2,3]
    expect(array.one? { |num| num.even?} ).to eq true
    expect(array.one? { |num| num.odd?} ).to eq false
  end

  it 'returns the first of an array' do
    array = [1,2,3]
    expect(array.first).to eq 1
  end

  it 'flattens results' do
    array = [1,2]
    expect(array.flat_map {|num| ['a', 'b']}).to eq ['a', 'b', 'a', 'b']
  end

  it 'groups an array by the result of a given requirement' do
    array = [1,2,3,4]
    expect(array.group_by {|num| num.odd? }).to eq ({true => [1,3], false => [2,4]})
    expect(array.group_by {|num| num % 2 }).to eq ({1 => [1,3], 0 => [2,4]})
  end

  it 'returns truthy or falsey if an array includes a given requirement' do
    array = [1,2,3,4]
    expect(array.include?(1)).to eq true
  end

  it 'carries out the iteration over each item in the array' do
    array = [1,2,3,4]
    expect(array.inject { |sum, n| sum + n}).to eq 10
  end

  it 'carries out the iteration over each item in the array' do
    array = [1,2,3,4]
    expect(array.reduce { |sum, n| sum + n}).to eq 10
  end

  it 'returns the sum of the elements in the array' do
    array = [1,2,3,4]
    expect(array.sum).to eq 10
    expect(array.sum {|num| num * 2 } ).to eq 20
  end

  it 'returns a new array with the result of the enumerator' do
    array = [1,2,3,4]
    expect(array.map {|num| num + 1}).to eq [2,3,4,5]
  end

  it 'returns result that has the maximum value resulting from the enumerator' do
    array = ['the','a', 'to','street']
    expect(array.max_by {|word| word.length}).to eq 'street'
  end

  it 'returns result that has the minimum value resulting from the enumerator' do
    array = ['the','a', 'to','street']
    expect(array.min_by {|word| word.length}).to eq 'a'
  end

  it 'returns true if the block never returns true for all the elements-truthy result' do
    array = [1,2,3,4,5]
    expect(array.none? {|num| num > 6}).to eq true
    expect(array.none? {|num| num <= 5}).to eq false
  end

  it 'returns an array of all elements for which the block returns false' do
    array = [1,2,3,4,5]
    expect(array.reject {|num| num.odd?}).to eq [2,4]
    expect(array.reject {|num| num.even?}).to eq [1,3,5]
  end

  it 'returns an array of all elements for which the block returns true' do
    array = [1,2,3,4,5]
    expect(array.select {|num| num.odd?}).to eq [1,3,5]
    expect(array.select {|num| num.even?}).to eq [2,4]
  end

  it 'returns an array of all elements sorted' do
    array = [60, 33, 24, 57, 2]
    expect(array.sort {|a,b| a <=> b}).to eq [2,24,33,57,60]
  end

  it 'Sorts enum using a set of keys generated by mapping the values in enum through the given block' do
    array = ['the','a', 'to','street']
    expect(array.sort_by {|word| word.length}).to eq ['a','to','the','street']
  end

  it 'returns the first (n) elements from enumerator' do
    array = [60, 33, 24, 57, 2]
    expect(array.take(2)).to eq [60,33]
    expect(array.take(4)).to eq [60,33,24,57]
  end

  it 'turns the result into an array' do
    range = 1..10
    expect(range.to_a).to eq [1,2,3,4,5,6,7,8,9,10]
  end

  it 'turns the result into a hash' do
    expect({:panda bamboo}.to_h).to eq {:panda => 'bamboo'}
  end

  it 'returns a new array removing duplicate values in the self' do
    array = [1,1,3,4,4,5]
    expect(array.uniq).to eq [1,3,4,5]
  end

end
